import { getCloudflareContext } from "@opennextjs/cloudflare";

// Typed access to Cloudflare bindings from any server context (routes, RSC).
// CloudflareEnv is generated by `npm run cf-typegen` from wrangler.jsonc.
export function env(): CloudflareEnv {
  return getCloudflareContext().env;
}

// Async variant for static/prerender contexts where the sync one isn't ready.
export async function envAsync(): Promise<CloudflareEnv> {
  const ctx = await getCloudflareContext({ async: true });
  return ctx.env;
}
